In [1]:
import pandas as pd
import numpy as np

In [2]:
from transformers import pipeline

In [4]:
df = pd.read_csv("/content/arabic_qa_sample.csv")
df.head()

,context,question,answer
0,القاهرة هي عاصمة مصر وتعد أكبر مدنها من حيث عد...,ما هي عاصمة مصر؟,القاهرة
1,نهر النيل هو أطول نهر في العالم ويمر عبر عدة د...,ما هو أطول نهر في العالم؟,نهر النيل
2,الذكاء الاصطناعي هو مجال من مجالات علوم الحاسب...,بماذا يهتم الذكاء الاصطناعي؟,ببناء أنظمة قادرة على التعلم واتخاذ القرار
3,جامعة الإسكندرية من الجامعات المصرية العريقة و...,أين تقع جامعة الإسكندرية؟,في مدينة الإسكندرية
4,الطاقة الشمسية تعتبر من أهم مصادر الطاقة المتج...,لماذا تعتبر الطاقة الشمسية مهمة؟,لأنها نظيفة ومستدامة

In [5]:
print("Shape:", df.shape)
print("\nMissing values:\n", df.isnull().sum())

Shape: (12, 3)

Missing values:
 context     0
question    0
answer      0
dtype: int64

In [6]:
df = df.dropna().drop_duplicates().reset_index(drop=True)
df

,context,question,answer
0,القاهرة هي عاصمة مصر وتعد أكبر مدنها من حيث عد...,ما هي عاصمة مصر؟,القاهرة
1,نهر النيل هو أطول نهر في العالم ويمر عبر عدة د...,ما هو أطول نهر في العالم؟,نهر النيل
2,الذكاء الاصطناعي هو مجال من مجالات علوم الحاسب...,بماذا يهتم الذكاء الاصطناعي؟,ببناء أنظمة قادرة على التعلم واتخاذ القرار
3,جامعة الإسكندرية من الجامعات المصرية العريقة و...,أين تقع جامعة الإسكندرية؟,في مدينة الإسكندرية
4,الطاقة الشمسية تعتبر من أهم مصادر الطاقة المتج...,لماذا تعتبر الطاقة الشمسية مهمة؟,لأنها نظيفة ومستدامة
5,بايثون لغة برمجة مشهورة تستخدم في تحليل البيان...,في ماذا تستخدم بايثون؟,في تحليل البيانات وتطوير تطبيقات الذكاء الاصطناعي
6,الإسكندرية مدينة ساحلية مصرية تقع على البحر ال...,على أي بحر تقع الإسكندرية؟,البحر المتوسط
7,تعتمد عملية تعلم الآلة على البيانات والخوارزمي...,على ماذا تعتمد عملية تعلم الآلة؟,على البيانات والخوارزميات
8,الأقصر من أهم المدن السياحية في مصر وتضم معابد...,لماذا تعد الأقصر مدينة مهمة سياحيا؟,لأنها تضم معابد وآثارا فرعونية شهيرة
9,تساعد قواعد البيانات في تخزين المعلومات وتنظيم...,ما فائدة قواعد البيانات؟,تخزين المعلومات وتنظيمها واسترجاعها بكفاءة
10,تستخدم الشبكات العصبية في مجالات متعددة مثل ال...,في أي مجالات تستخدم الشبكات العصبية؟,التعرف على الصور ومعالجة اللغة الطبيعية
11,يعد تعلم البرمجة مهارة مهمة لأنه يساعد على حل ...,لماذا يعد تعلم البرمجة مهما؟,لأنه يساعد على حل المشكلات وبناء تطبيقات مفيدة

In [7]:
qa_pipeline = pipeline("question-answering", model="deepset/xlm-roberta-base-squad2")

/usr/local/lib/python3.12/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning:
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(

config.json:   0%|          | 0.00/605 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

model.safetensors:   0%|          | 0.00/1.11G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/199 [00:00<?, ?it/s]

XLMRobertaForQuestionAnswering LOAD REPORT from: deepset/xlm-roberta-base-squad2
Key                             | Status     |  |
--------------------------------+------------+--+-
roberta.embeddings.position_ids | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/79.0 [00:00<?, ?B/s]

sentencepiece.bpe.model:   0%|          | 0.00/5.07M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/150 [00:00<?, ?B/s]

In [8]:
sample_context = df.loc[0, "context"]
sample_question = df.loc[0, "question"]

result = qa_pipeline(question=sample_question, context=sample_context)
result

{'score': 0.4233783185482025, 'start': 0, 'end': 7, 'answer': 'القاهرة'}

In [9]:
print("Question:", sample_question)
print("Context:", sample_context)
print("Predicted Answer:", result["answer"])
print("Expected Answer:", df.loc[0, "answer"])

Question: ما هي عاصمة مصر؟
Context: القاهرة هي عاصمة مصر وتعد أكبر مدنها من حيث عدد السكان.
Predicted Answer: القاهرة
Expected Answer: القاهرة

In [10]:
predictions = []

for _, row in df.iterrows():
    result = qa_pipeline(question=row["question"], context=row["context"])
    predictions.append(result["answer"])

df["predicted_answer"] = predictions
df

,context,question,answer,predicted_answer
0,القاهرة هي عاصمة مصر وتعد أكبر مدنها من حيث عد...,ما هي عاصمة مصر؟,القاهرة,القاهرة
1,نهر النيل هو أطول نهر في العالم ويمر عبر عدة د...,ما هو أطول نهر في العالم؟,نهر النيل,نهر النيل
2,الذكاء الاصطناعي هو مجال من مجالات علوم الحاسب...,بماذا يهتم الذكاء الاصطناعي؟,ببناء أنظمة قادرة على التعلم واتخاذ القرار,ببناء أنظمة قادرة على التعلم واتخاذ القرار.
3,جامعة الإسكندرية من الجامعات المصرية العريقة و...,أين تقع جامعة الإسكندرية؟,في مدينة الإسكندرية,مدينة الإسكندرية.
4,الطاقة الشمسية تعتبر من أهم مصادر الطاقة المتج...,لماذا تعتبر الطاقة الشمسية مهمة؟,لأنها نظيفة ومستدامة,لأنها نظيفة ومستدامة.
5,بايثون لغة برمجة مشهورة تستخدم في تحليل البيان...,في ماذا تستخدم بايثون؟,في تحليل البيانات وتطوير تطبيقات الذكاء الاصطناعي,تحليل البيانات وتطوير تطبيقات الذكاء الاصطناعي.
6,الإسكندرية مدينة ساحلية مصرية تقع على البحر ال...,على أي بحر تقع الإسكندرية؟,البحر المتوسط,البحر المتوسط
7,تعتمد عملية تعلم الآلة على البيانات والخوارزمي...,على ماذا تعتمد عملية تعلم الآلة؟,على البيانات والخوارزميات,البيانات والخوارزميات
8,الأقصر من أهم المدن السياحية في مصر وتضم معابد...,لماذا تعد الأقصر مدينة مهمة سياحيا؟,لأنها تضم معابد وآثارا فرعونية شهيرة,الأقصر من أهم المدن السياحية في مصر
9,تساعد قواعد البيانات في تخزين المعلومات وتنظيم...,ما فائدة قواعد البيانات؟,تخزين المعلومات وتنظيمها واسترجاعها بكفاءة,تساعد قواعد البيانات في تخزين المعلومات وتنظيم...
10,تستخدم الشبكات العصبية في مجالات متعددة مثل ال...,في أي مجالات تستخدم الشبكات العصبية؟,التعرف على الصور ومعالجة اللغة الطبيعية,التعرف على الصور ومعالجة اللغة الطبيعية.
11,يعد تعلم البرمجة مهارة مهمة لأنه يساعد على حل ...,لماذا يعد تعلم البرمجة مهما؟,لأنه يساعد على حل المشكلات وبناء تطبيقات مفيدة,حل المشكلات

In [11]:
def normalize_text(text):
    return str(text).strip().replace("ـ", "").replace("  ", " ")

df["answer_norm"] = df["answer"].apply(normalize_text)
df["predicted_norm"] = df["predicted_answer"].apply(normalize_text)

df["exact_match"] = (df["answer_norm"] == df["predicted_norm"]).astype(int)

accuracy = df["exact_match"].mean()
print("Exact Match Accuracy:", accuracy)

Exact Match Accuracy: 0.25

In [12]:
df[["question", "answer", "predicted_answer", "exact_match"]]

,question,answer,predicted_answer,exact_match
0,ما هي عاصمة مصر؟,القاهرة,القاهرة,1
1,ما هو أطول نهر في العالم؟,نهر النيل,نهر النيل,1
2,بماذا يهتم الذكاء الاصطناعي؟,ببناء أنظمة قادرة على التعلم واتخاذ القرار,ببناء أنظمة قادرة على التعلم واتخاذ القرار.,0
3,أين تقع جامعة الإسكندرية؟,في مدينة الإسكندرية,مدينة الإسكندرية.,0
4,لماذا تعتبر الطاقة الشمسية مهمة؟,لأنها نظيفة ومستدامة,لأنها نظيفة ومستدامة.,0
5,في ماذا تستخدم بايثون؟,في تحليل البيانات وتطوير تطبيقات الذكاء الاصطناعي,تحليل البيانات وتطوير تطبيقات الذكاء الاصطناعي.,0
6,على أي بحر تقع الإسكندرية؟,البحر المتوسط,البحر المتوسط,1
7,على ماذا تعتمد عملية تعلم الآلة؟,على البيانات والخوارزميات,البيانات والخوارزميات,0
8,لماذا تعد الأقصر مدينة مهمة سياحيا؟,لأنها تضم معابد وآثارا فرعونية شهيرة,الأقصر من أهم المدن السياحية في مصر,0
9,ما فائدة قواعد البيانات؟,تخزين المعلومات وتنظيمها واسترجاعها بكفاءة,تساعد قواعد البيانات في تخزين المعلومات وتنظيم...,0
10,في أي مجالات تستخدم الشبكات العصبية؟,التعرف على الصور ومعالجة اللغة الطبيعية,التعرف على الصور ومعالجة اللغة الطبيعية.,0
11,لماذا يعد تعلم البرمجة مهما؟,لأنه يساعد على حل المشكلات وبناء تطبيقات مفيدة,حل المشكلات,0

In [13]:
df[df["exact_match"] == 0][["context", "question", "answer", "predicted_answer"]]

,context,question,answer,predicted_answer
2,الذكاء الاصطناعي هو مجال من مجالات علوم الحاسب...,بماذا يهتم الذكاء الاصطناعي؟,ببناء أنظمة قادرة على التعلم واتخاذ القرار,ببناء أنظمة قادرة على التعلم واتخاذ القرار.
3,جامعة الإسكندرية من الجامعات المصرية العريقة و...,أين تقع جامعة الإسكندرية؟,في مدينة الإسكندرية,مدينة الإسكندرية.
4,الطاقة الشمسية تعتبر من أهم مصادر الطاقة المتج...,لماذا تعتبر الطاقة الشمسية مهمة؟,لأنها نظيفة ومستدامة,لأنها نظيفة ومستدامة.
5,بايثون لغة برمجة مشهورة تستخدم في تحليل البيان...,في ماذا تستخدم بايثون؟,في تحليل البيانات وتطوير تطبيقات الذكاء الاصطناعي,تحليل البيانات وتطوير تطبيقات الذكاء الاصطناعي.
7,تعتمد عملية تعلم الآلة على البيانات والخوارزمي...,على ماذا تعتمد عملية تعلم الآلة؟,على البيانات والخوارزميات,البيانات والخوارزميات
8,الأقصر من أهم المدن السياحية في مصر وتضم معابد...,لماذا تعد الأقصر مدينة مهمة سياحيا؟,لأنها تضم معابد وآثارا فرعونية شهيرة,الأقصر من أهم المدن السياحية في مصر
9,تساعد قواعد البيانات في تخزين المعلومات وتنظيم...,ما فائدة قواعد البيانات؟,تخزين المعلومات وتنظيمها واسترجاعها بكفاءة,تساعد قواعد البيانات في تخزين المعلومات وتنظيم...
10,تستخدم الشبكات العصبية في مجالات متعددة مثل ال...,في أي مجالات تستخدم الشبكات العصبية؟,التعرف على الصور ومعالجة اللغة الطبيعية,التعرف على الصور ومعالجة اللغة الطبيعية.
11,يعد تعلم البرمجة مهارة مهمة لأنه يساعد على حل ...,لماذا يعد تعلم البرمجة مهما؟,لأنه يساعد على حل المشكلات وبناء تطبيقات مفيدة,حل المشكلات

## Conclusion

This project demonstrates how transformer models can be used for Arabic question answering.

Main steps included:
- preparing Arabic context-question-answer samples
- applying a pretrained transformer model
- generating answer spans automatically
- evaluating predictions with exact match accuracy

This project highlights the use of NLP transformers for Arabic language understanding tasks.